# Generated by Django 2.1.5 on 2019-03-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20190316_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200)),
            ],
        ),
    ]
