# Generated by Django 2.1.5 on 2019-03-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_question_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_list',
            name='question_num',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
