# Generated by Django 2.1.5 on 2019-03-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_question_list_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_list_id',
            field=models.IntegerField(default=0),
        ),
    ]
